baseURL = "https://www.spicychicken.quest/"
languageCode = "en-us"
title = "Spicy Chicken Quest"
theme = "hugo-learn-theme"
description = "FFXIV Tips, Tricks, and Stuff"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
author = "Tirzah Grant of Chaos Omega"
description = "Guides, Tips, TLDRs, and more...SpicyChicken Quest is inspired and named after a member of the Free Company Aspects of Love on Chaos Omega in Final Fantasy XIV."
showVisitedLinks = true
disableSearch = false
themeVariant = "mine"

landingPageName = "â¤ï¸ Home â¤ï¸"

[[menu.shortcuts]]
name = "ğŸ—ºï¸ FFXIV Hunt Log Path Finder"
url = "https://hunts.spicychicken.quest"
weight = 20

[[menu.shortcuts]]
name="ğŸ“‘ Git Involved"
url = "/git-involved/"
weight = 40

[[menu.shortcuts]]
name="ğŸ“‘ Changelog"
url = "/changelog/"
weight = 41

[[menu.shortcuts]]
name="ğŸ™‹ Suggestions"
url = "/feedback"
weight = 50

[[menu.shortcuts]]
name="â¤ï¸ Contributors"
url = "/contributors"
weight = 60